######################################################################
# Automatically generated by qmake (3.1) Wed Apr 18 11:50:31 2018
######################################################################

TEMPLATE = app
TARGET = spectre
#find . -type d
INCLUDEPATH += . ./src ./src/obj ./src/test ./src/test/other ./src/test/data ./src/wordlists ./src/qt ./src/qt/res ./src/qt/res/css ./src/qt/res/css/fonts ./src/qt/res/images ./src/qt/res/images/avatars ./src/qt/res/icons ./src/qt/res/assets ./src/qt/res/assets/css ./src/qt/res/assets/plugins ./src/qt/res/assets/plugins/md5 ./src/qt/res/assets/plugins/identicon ./src/qt/res/assets/plugins/boostrapv3 ./src/qt/res/assets/plugins/boostrapv3/css ./src/qt/res/assets/plugins/boostrapv3/js ./src/qt/res/assets/plugins/boostrapv3/fonts ./src/qt/res/assets/plugins/framework ./src/qt/res/assets/plugins/markdown ./src/qt/res/assets/plugins/shajs ./src/qt/res/assets/plugins/pnglib ./src/qt/res/assets/plugins/iscroll ./src/qt/res/assets/plugins/jquery ./src/qt/res/assets/plugins/classie ./src/qt/res/assets/plugins/pace ./src/qt/res/assets/plugins/contextMenu ./src/qt/res/assets/plugins/jquery-scrollbar ./src/qt/res/assets/plugins/jdenticon ./src/qt/res/assets/plugins/qrcode ./src/qt/res/assets/plugins/emojione ./src/qt/res/assets/plugins/emojione/assets ./src/qt/res/assets/plugins/emojione/assets/svg ./src/qt/res/assets/plugins/emojione/assets/css ./src/qt/res/assets/plugins/jquery-transit ./src/qt/res/assets/plugins/footable ./src/qt/res/assets/plugins/jquery-ui ./src/qt/res/assets/plugins/jquery-ui/images ./src/qt/res/assets/js ./src/qt/res/assets/js/pages ./src/qt/res/assets/img ./src/qt/res/assets/img/progress ./src/qt/res/assets/img/avatars ./src/qt/res/assets/icons ./src/qt/res/assets/fonts ./src/qt/res/assets/fonts/Framework-icon ./src/qt/res/assets/fonts/FontAwesome ./src/qt/res/assets/fonts/Montserrat ./src/qt/res/assets/fonts/Footable ./src/qt/res/src ./src/qt/locale ./src/qt/forms ./src/qt/test ./src/lz4 ./src/json ./src/xxhash ./src/obj-test
QT += testlib webenginewidgets webchannel
CONFIG += c++11

RESOURCES += \
    spectre.qrc

HEADERS += \
    src/json/json_spirit.h \
    src/json/json_spirit_error_position.h \
    src/json/json_spirit_reader.h \
    src/json/json_spirit_reader_template.h \
    src/json/json_spirit_stream_reader.h \
    src/json/json_spirit_utils.h \
    src/json/json_spirit_value.h \
    src/json/json_spirit_writer.h \
    src/json/json_spirit_writer_template.h \
    src/lz4/lz4.h \
    src/qt/test/uritests.h \
    src/qt/aboutdialog.h \
    src/qt/addresstablemodel.h \
    src/qt/askpassphrasedialog.h \
    src/qt/bitcoinaddressvalidator.h \
    src/qt/bitcoinamountfield.h \
    src/qt/bitcoinunits.h \
    src/qt/bridgetranslations.h \
    src/qt/clientmodel.h \
    src/qt/coincontroldialog.h \
    src/qt/coincontroltreewidget.h \
    src/qt/csvmodelwriter.h \
    src/qt/editaddressdialog.h \
    src/qt/guiconstants.h \
    src/qt/guiutil.h \
    src/qt/macdockiconhandler.h \
    src/qt/macnotificationhandler.h \
    src/qt/messagemodel.h \
    src/qt/monitoreddatamapper.h \
    src/qt/notificator.h \
    src/qt/optionsmodel.h \
    src/qt/paymentserver.h \
    src/qt/peertablemodel.h \
    src/qt/qvalidatedlineedit.h \
    src/qt/qvaluecombobox.h \
    src/qt/rpcconsole.h \
    src/qt/scicon.h \
    src/qt/spectrebridge.h \
    src/qt/spectregui.h \
    src/qt/trafficgraphwidget.h \
    src/qt/transactiondesc.h \
    src/qt/transactionrecord.h \
    src/qt/transactiontablemodel.h \
    src/qt/walletmodel.h \
    src/wordlists/chinese_simplified.h \
    src/wordlists/chinese_traditional.h \
    src/wordlists/english.h \
    src/wordlists/french.h \
    src/wordlists/japanese.h \
    src/wordlists/spanish.h \
    src/xxhash/xxhash.h \
    src/addrman.h \
    src/alert.h \
    src/allocators.h \
    src/anonymize.h \
    src/base58.h \
    src/bignum.h \
    src/bloom.h \
    src/chainparams.h \
    src/chainparamsseeds.h \
    src/checkpoints.h \
    src/clientversion.h \
    src/coincontrol.h \
    src/compat.h \
    src/core.h \
    src/crypter.h \
    src/db.h \
    src/eckey.h \
    src/extkey.h \
    src/hash.h \
    src/init.h \
    src/kernel.h \
    src/key.h \
    src/keystore.h \
    src/main.h \
    src/miner.h \
    src/mruset.h \
    src/net.h \
    src/netbase.h \
    src/pbkdf2.h \
    src/protocol.h \
    src/ringsig.h \
    src/rpcclient.h \
    src/rpcprotocol.h \
    src/rpcserver.h \
    src/script.h \
    src/scrypt.h \
    src/serialize.h \
    src/smessage.h \
    src/state.h \
    src/stealth.h \
    src/strlcpy.h \
    src/sync.h \
    src/threadsafety.h \
    src/tinyformat.h \
    src/txdb-leveldb.h \
    src/txdb.h \
    src/txmempool.h \
    src/types.h \
    src/ui_interface.h \
    src/uint256.h \
    src/util.h \
    src/version.h \
    src/wallet.h \
    src/walletdb.h \
    leveldb/helpers/memenv/memenv.h

SOURCES += \
    src/json/json_spirit_reader.cpp \
    src/json/json_spirit_value.cpp \
    src/json/json_spirit_writer.cpp \
    src/qt/test/test_main.cpp \
    src/qt/test/uritests.cpp \
    src/qt/aboutdialog.cpp \
    src/qt/addresstablemodel.cpp \
    src/qt/askpassphrasedialog.cpp \
    src/qt/bitcoinaddressvalidator.cpp \
    src/qt/bitcoinamountfield.cpp \
    src/qt/bitcoinstrings.cpp \
    src/qt/bitcoinunits.cpp \
    src/qt/clientmodel.cpp \
    src/qt/coincontroldialog.cpp \
    src/qt/coincontroltreewidget.cpp \
    src/qt/csvmodelwriter.cpp \
    src/qt/editaddressdialog.cpp \
    src/qt/guiutil.cpp \
    src/qt/messagemodel.cpp \
    src/qt/monitoreddatamapper.cpp \
    src/qt/notificator.cpp \
    src/qt/optionsmodel.cpp \
    src/qt/paymentserver.cpp \
    src/qt/peertablemodel.cpp \
    src/qt/qvalidatedlineedit.cpp \
    src/qt/qvaluecombobox.cpp \
    src/qt/rpcconsole.cpp \
    src/qt/scicon.cpp \
    src/qt/spectre.cpp \
    src/qt/spectrebridge.cpp \
    src/qt/spectregui.cpp \
    src/qt/trafficgraphwidget.cpp \
    src/qt/transactiondesc.cpp \
    src/qt/transactionrecord.cpp \
    src/qt/transactiontablemodel.cpp \
    src/qt/walletmodel.cpp \
#    src/test/other/DoS_tests.cpp \
#    src/test/other/miner_tests.cpp \
#    src/test/other/transaction_tests.cpp \
#    src/test/accounting_tests.cpp \
#    src/test/allocator_tests.cpp \
#    src/test/base32_tests.cpp \
#    src/test/base58_tests.cpp \
#    src/test/base64_tests.cpp \
#    src/test/basic_tests.cpp \
#    src/test/bignum_tests.cpp \
#    src/test/bip32_tests.cpp \
#    src/test/Checkpoints_tests.cpp \
#    src/test/extkey_tests.cpp \
#    src/test/getarg_tests.cpp \
#    src/test/hash_tests.cpp \
#    src/test/hmac_tests.cpp \
#    src/test/key_tests.cpp \
#    src/test/mnemonic_tests.cpp \
#    src/test/mruset_tests.cpp \
#    src/test/multisig_tests.cpp \
#    src/test/netbase_tests.cpp \
#    src/test/ringsig_tests.cpp \
#    src/test/rpc_tests.cpp \
#    src/test/script_P2SH_tests.cpp \
#    src/test/script_tests.cpp \
#    src/test/sigopcount_tests.cpp \
#    src/test/smsg_tests.cpp \
#    src/test/stealth_tests.cpp \
#    src/test/test_shadow.cpp \
#    src/test/uint160_tests.cpp \
#    src/test/uint256_tests.cpp \
#    src/test/util_tests.cpp \
#    src/test/wallet_tests.cpp \
    src/addrman.cpp \
    src/alert.cpp \
    src/anonymize.cpp \
    src/bloom.cpp \
    src/chainparams.cpp \
    src/checkpoints.cpp \
    src/core.cpp \
    src/crypter.cpp \
    src/db.cpp \
    src/eckey.cpp \
    src/extkey.cpp \
    src/hash.cpp \
    src/init.cpp \
    src/kernel.cpp \
    src/key.cpp \
    src/keystore.cpp \
    src/main.cpp \
    src/miner.cpp \
    src/net.cpp \
    src/netbase.cpp \
    src/noui.cpp \
    src/pbkdf2.cpp \
    src/protocol.cpp \
    src/ringsig.cpp \
    src/rpcblockchain.cpp \
    src/rpcclient.cpp \
    src/rpcdump.cpp \
    src/rpcextkey.cpp \
    src/rpcmining.cpp \
    src/rpcmnemonic.cpp \
    src/rpcnet.cpp \
    src/rpcprotocol.cpp \
    src/rpcrawtransaction.cpp \
    src/rpcserver.cpp \
    src/rpcsmessage.cpp \
    src/rpcwallet.cpp \
    src/script.cpp \
    src/scrypt.cpp \
    src/smessage.cpp \
    src/spectrecoind.cpp \
    src/state.cpp \
    src/stealth.cpp \
    src/sync.cpp \
    src/txdb-leveldb.cpp \
    src/txmempool.cpp \
    src/util.cpp \
    src/version.cpp \
    src/wallet.cpp \
    src/walletdb.cpp \
    src/lz4/lz4.c \
    src/xxhash/xxhash.c \
    leveldb/helpers/memenv/memenv.cc \
    src/qt/macdockiconhandler.mm \
    src/qt/macnotificationhandler.mm \

INCLUDEPATH += leveldb/include leveldb/helpers db4.8/build_unix

DEFINES += FORTIFY_SOURCE=1
QMAKE_CXXFLAGS += -pthread -fPIC -fstack-protector -O2 \
              -D_FORTIFY_SOURCE=1 \
              -Wall -Wextra -Wno-ignored-qualifiers -Woverloaded-virtual \
              -Wformat -Wformat-security -Wno-unused-parameter

LIBS += leveldb/out-static/libmemenv.a \
                     leveldb/out-static/libleveldb.a \
                     db4.8/build_unix/libdb_cxx.a \
                     tor/src/or/libtor.a \
                     tor/src/common/libor.a \
                     tor/src/common/libor-ctime.a \
                     tor/src/common/libor-crypto.a \
                     tor/src/common/libor-event.a \
                     tor/src/trunnel/libor-trunnel.a \
                     tor/src/common/libcurve25519_donna.a \
                     tor/src/ext/ed25519/donna/libed25519_donna.a \
                     tor/src/ext/ed25519/ref10/libed25519_ref10.a \
                     tor/src/ext/keccak-tiny/libkeccak-tiny.a \

macx {
    DEFINES += MAC_OSX
    QMAKE_CXXFLAGS += -std=c++14 -mmacosx-version-min=10.10

    #add in core foundation framework
    QMAKE_LFLAGS += -F /System/Library/Frameworks/CoreFoundation.framework/
    LIBS += -framework CoreFoundation

    QMAKE_LFLAGS += -F /System/Library/Frameworks/AppKit.framework/
    LIBS += -framework AppKit

    QMAKE_LFLAGS += -F /System/Library/Frameworks/ApplicationServices.framework/
    LIBS += -framework ApplicationServices
    # Mac: compile for maximum compatibility (10.5, 32-bit)
    macx:QMAKE_CXXFLAGS += -mmacosx-version-min=10.5 -isysroot

    #brew install boost
    _BOOST_PATH = /usr/local/Cellar/boost/1.67.0_1
    INCLUDEPATH += "$${_BOOST_PATH}/include/"
    LIBS += -L$${_BOOST_PATH}/lib
    LIBS += -lboost_system-mt -lboost_chrono-mt -lboost_filesystem-mt -lboost_program_options-mt -lboost_thread-mt # using dynamic lib (not sure if you need that "-mt" at the end or not)
    DEFINES += BOOST_ASIO_ENABLE_OLD_SERVICES BOOST_SPIRIT_THREADSAFE BOOST_THREAD_USE_LIB
    #LIBS += $${_BOOST_PATH}/lib/libboost_chrono-mt.a # using static lib

    #brew install openssl@1.1
    _OPENSSL_PATH = /usr/local/opt/openssl@1.1
    INCLUDEPATH += "$${_OPENSSL_PATH}/include/"
    LIBS += -L$${_OPENSSL_PATH}/lib
    LIBS += -lssl -lcrypto # using dynamic lib (not sure if you need that "-mt" at the end or not)

    #brew install berkeley-db@4
    _BERKELEYDB4_8_PATH = /usr/local/opt/berkeley-db@4
    INCLUDEPATH += "$${_BERKELEYDB4_8_PATH}/include/"
    LIBS += -L$${_BERKELEYDB4_8_PATH}/lib
    LIBS += -ldb-4.8 -ldb -ldb_cxx -ldb_cxx-4.8

    #brew install leveldb
    _LEVELDB_PATH = /usr/local/Cellar/leveldb/1.20_2
    INCLUDEPATH += "$${_LEVELDB_PATH}/include/"
    LIBS += -L$${_LEVELDB_PATH}/lib
    LIBS += -lleveldb
    DEFINES += LEVELDB_PLATFORM_POSIX OS_MACOSX

    #libevent-2.1.6.dylib
    #brew install libevent
    _LIBEVENT_PATH = /usr/local/Cellar/libevent/2.1.8
    INCLUDEPATH += "$${_LIBEVENT_PATH}/include/"
    LIBS += -L$${_LIBEVENT_PATH}/lib
    #Shblis-MacBook-Pro:src Shbli$ find /usr/local/Cellar/libevent/2.1.8/lib/ -name *a
    LIBS += -levent_extra -levent -levent_core -levent_openssl -levent_pthreads

#    #brew install lua
#    _LUA_PATH = /usr/local/Cellar/lua/5.3.4_3
#    INCLUDEPATH += "$${_LUA_PATH}/include/"
#    LIBS += -L$${_LUA_PATH}/lib
#    #Shblis-MacBook-Pro:src Shbli$ find /usr/local/Cellar/libevent/2.1.8/lib/ -name *a
#    LIBS += -levent_extra -levent -levent_core -levent_openssl -levent_pthreads
}

FORMS += \
    src/qt/forms/aboutdialog.ui \
    src/qt/forms/askpassphrasedialog.ui \
    src/qt/forms/coincontroldialog.ui \
    src/qt/forms/editaddressdialog.ui \
    src/qt/forms/rpcconsole.ui \
    src/qt/forms/transactiondescdialog.ui

include(tor.pro)
