# SPDX-FileCopyrightText: © 2020 Alias Developers
# SPDX-FileCopyrightText: © 2016 SpectreCoin Developers
#
# SPDX-License-Identifier: MIT

### At first perform source build ###
FROM aliascash/aliaswallet-builder-ubuntu-18-04:1.7 as build
MAINTAINER HLXEasy <hlxeasy@gmail.com>

# Build parameters
ARG BUILD_THREADS="6"

# Runtime parameters
ENV BUILD_THREADS=$BUILD_THREADS

COPY . /aliaswallet

RUN cd /aliaswallet \
 && mkdir db4.8 leveldb \
 && ./autogen.sh \
 && ./configure \
        --enable-gui \
 && make -j${BUILD_THREADS} \
 && strip /aliaswallet/src/aliaswalletd \
 && strip /aliaswallet/src/aliaswallet

### Now upload binaries to GitHub ###
FROM aliascash/github-uploader:latest
MAINTAINER HLXEasy <hlxeasy@gmail.com>

ARG GITHUB_TOKEN=1234567
ARG ALIASWALLET_RELEASE=latest
ARG ALIASWALLET_REPOSITORY=aliaswallet
ARG GIT_COMMIT=unknown
ARG REPLACE_EXISTING_ARCHIVE=''
#ENV GITHUB_TOKEN=${GITHUB_TOKEN}
ENV ARCHIVE=Aliaswallet-${ALIASWALLET_RELEASE}-${GIT_COMMIT}-Ubuntu-18-04.tgz
ENV CHKSUM_FILE=Checksum-Aliaswallet-Ubuntu-18-04.txt

RUN mkdir -p /filesToUpload/usr/local/bin

COPY --from=build /aliaswallet/src/aliaswalletd /filesToUpload/usr/local/bin/
COPY --from=build /aliaswallet/src/aliaswallet /filesToUpload/usr/local/bin/
COPY --from=build /aliaswallet/scripts/createChecksums.sh /tmp/

RUN cd /filesToUpload \
 && tar czf ${ARCHIVE} . \
 && github-release upload \
        --user spectrecoin \
        --security-token "${GITHUB_TOKEN}" \
        --repo "${ALIASWALLET_REPOSITORY}" \
        --tag "${ALIASWALLET_RELEASE}" \
        --name "${ARCHIVE}" \
        --file "/filesToUpload/${ARCHIVE}" \
        ${REPLACE_EXISTING_ARCHIVE} \
 && chmod +x /tmp/createChecksums.sh \
 && sh /tmp/createChecksums.sh /filesToUpload/${ARCHIVE} ${CHKSUM_FILE} \
 && export GITHUB_TOKEN=---
