# SPDX-FileCopyrightText: © 2020 Alias Developers
# SPDX-FileCopyrightText: © 2016 SpectreCoin Developers
#
# SPDX-License-Identifier: MIT

### At first perform source build ###
FROM aliascash/alias-wallet-builder-android:latest
MAINTAINER HLXEasy <hlxeasy@gmail.com>

# Build parameters
ARG BUILD_THREADS="6"
ARG KEYSTORE_PASS="123456"

# Runtime parameters
ENV BUILD_THREADS=${BUILD_THREADS}
ENV KEYSTORE_PASS=${KEYSTORE_PASS}

COPY . /alias-wallet

WORKDIR /alias-wallet/

RUN ./scripts/cmake-build-android_arm64.sh -t ${BUILD_THREADS} \
 && ./scripts/cmake-build-android_armv7.sh -t ${BUILD_THREADS} \
 && ./scripts/cmake-build-android_x86-64.sh -t ${BUILD_THREADS} \
 && /root/Archives/Android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/aarch64-linux-android/bin/strip ./cmake-build-cmdline-android22_arm64/aliaswallet/src/aliaswalletd \
 && /root/Archives/Android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/arm-linux-androideabi/bin/strip ./cmake-build-cmdline-android22_armv7a/aliaswallet/src/aliaswalletd \
 && /root/Archives/Android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/x86_64-linux-android/bin/strip  ./cmake-build-cmdline-android22_x86_64/aliaswallet/src/aliaswalletd

RUN ./scripts/android-prepare-env_CI.sh \
 && ./scripts/android-build.sh
